config/routes.rb
Rails.application.routes.draw do

  resources :permissions
  resources :roles
  resources :posts
  devise_for :users
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
        user ||= User.new(role_id: '2') # guest user (not logged in)

      if user.role_id == 3
          can :read, :all
          can :manage, Post, user_id:user.id
        else
          if user.role_id == 1
            can :manage, :all
            else
          can :read, :all
        end
      end
    end
end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?a/
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :role_perms
  has_many :roles, :through => :role_perms
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
  has_many :role_perms
  has_many :permissions, :through => :role_perms
end

app/models/role_perm.rb
class RolePerm < ApplicationRecord
  belongs_to :roles
  belongs_to :permissions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  belongs_to :role
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]

  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:label, :value)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :post_title, :post_content, :post_thumbnail_url)
    end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:role_name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    #load_and_authorize_resource :class => WelcomeController

  def index
      @posts = Post.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Producthunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  </head>

  <body>
    <div class="bodywrapper">
      <header>
        <div class="wrapper_left">
          <div class="producthuntlogo"><p> P </p></div>
          <div class="pagetitle">Producthunt</div>
        </div>

        <div class="wrapper_right">
          <div class="search">
            <div class="searchicon"> <i class="fa fa-search" aria-hidden="true"></i> </div>
            <input type="text" class="searchterm" placeholder="search for a product"></input>
            <div class="clearicon"> <i class="fa fa-times" aria-hidden="true"></i> </div>
          </div>
          <div class="login">
          <% if user_signed_in?%>
        <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        <% else %>
        <%= link_to "login", new_user_session_path %>
        <% end %>
        </div>
          <div class="loginicon"><p>+</p> </div>
        </div>
      </header>

      <nav>
        <div class="navitem">
          <div class="innernavitem">
            <span>Tech</span>
          </div>
        </div>
        <div class="navitem">
          <div class="innernavitem">
            <span>Games</span>
          </div>
        </div>
        <div class="navitem">
            <div class="innernavitem">
              <span>Collections</span>
            </div>
        </div>
      </nav>
      <p class="notice"><%= notice %></p>
     <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
  </body>

  <script>
    $('.search > *')
        .focus(function() {
            $('.search').toggleClass('focused');
        })
        .blur(function() {
            $('.search').toggleClass('focused');
        });
  </script>
</html>

app/views/permissions/_form.html.erb
<%= form_with(model: permission, local: true) do |form| %>
  <% if permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label, id: :permission_label %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :permission_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permissions</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= permission.label %></td>
        <td><%= permission.value %></td>
        <td><%= link_to 'Show', permission %></td>
        <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
        <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permission', new_permission_path %>

app/views/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Back', permissions_path %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @permission.label %>
</p>

<p>
  <strong>Value:</strong>
  <%= @permission.value %>
</p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :post_title %>
    <%= form.text_area :post_title, id: :post_Post_title %>
  </div>

  <div class="field">
    <%= form.label :post_content %>
    <%= form.text_area :post_content, id: :post_post_content %>
  </div>

  <div class="field">
    <%= form.label :post_thumbnail_url %>
    <%= form.text_area :post_thumbnail_url, id: :post_post_thumbnail_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post title</th>
      <th>Post content</th>
      <th>Post thumbnail url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.post_title %></td>
        <td><%= post.post_content %></td>
        <td><%= post.post_thumbnail_url %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Post title:</strong>
  <%= @post.post_title %>
</p>

<p>
  <strong>Post content:</strong>
  <%= @post.post_content %>
</p>

<p>
  <strong>Post thumbnail url:</strong>
  <%= @post.post_thumbnail_url %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/roles/_form.html.erb
<%= form_with(model: role, local: true) do |form| %>
  <% if role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :role_name %>
    <%= form.text_field :role_name, id: :role_role_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

  <% for permission in Permission.all %>
<div>
  <%= check_box_tag "role[permission_ids][]", permission.id, @role.permissions.include?(permission) %>
  <%=h permission.name %>
</div>
<% end %>
<%= hidden_field_tag "role[permission_ids][]", "" %>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Roles</h1>

<table>
  <thead>
    <tr>
      <th>Role name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.role_name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form', role: @role %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Role name:</strong>
  <%= @role.role_name %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>

app/views/welcome/index.html.erb
<main>
  <div>
      <div class="date"> <h1>TODAY <span> actual date </span></h1></div>

      <% @posts.each do |post| %>
        <%= link_to post_path(post) do %>
          <div class="product" >
              <div class="votes">
                <div class="votesubdiv"><i class="fa fa-chevron-up" aria-hidden="true"></i></div>
                <div class="votesubdiv">1234</div>
                <div class="votesubdiv"><i class="fa fa-chevron-down" aria-hidden="true"></i></div>
              </div>
              <div class="content">
                <div class="productname"> <%= post.post_title %></div>
                <div class="productdesc"> <%= post.post_content %> </div>
              </div>
              <div class="avatar"><img class="img-circle" src="<%= post.post_thumbnail_url %>" height=40 width=40> </div>
              <div class="comments"><i class="fa fa-comment-o" aria-hidden="true"></i> ### </div>
          </div>
     <% end %>

      <% if can? :update, post %>
        <%= link_to "Edit", edit_post_path(post) %>
      <% end %>
      <% if can? :destroy, post %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>


      <% end %>


      </div>
  </main>